<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>
			net20;net35;net40;net45;net46;net47;net48;
			netstandard2.0;netstandard2.1;
			net8.0;
		</TargetFrameworks>

		<!--project-->
		<RootNamespace>Cave.IO</RootNamespace>
		<AssemblyOriginatorKeyFile>cave-io.snk</AssemblyOriginatorKeyFile>
		<Product>CaveSystems IO Library</Product>
		<PackageTags>CaveSystems IO</PackageTags>
		<Description>Multi-targeted .NET library focused on fast, low-overhead data handling. It provides tools commonly needed in protocol stacks, file formats, embedded systems, and performance-sensitive backend systems.</Description>
		<PackageProjectUrl>https://github.com/CaveSystems/cave-io</PackageProjectUrl>
		<RepositoryUrl>https://github.com/CaveSystems/cave-io</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!--settings-->
		<PackageReleaseNotes />
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<SignAssembly>true</SignAssembly>
		<NeutralLanguage />
		<DelaySign>false</DelaySign>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(SolutionDir)\README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Cave.Extensions" />
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="System.Reflection.Emit.Lightweight" />
		<PackageReference Include="System.Memory" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net47' OR '$(TargetFramework)' == 'net48'">
		<PackageReference Include="System.Memory" />
	</ItemGroup>

</Project>
